
networks:
  service:
    name: buchungsverwaltung-service-main
  architecture:
    name: main

services:

  rest-api-buchungsverwaltung1:
    networks:
      - service
      - architecture
    build: ./rest_api
    container_name: rest-api-buchungsverwaltung1
    environment:
      - DBUSER=admin
      - DBPWD=test1234
      - MONGODBROUTER=mongodb://buchungsverwaltung-single-db
      - ROOTPW=test
      - RECHNUNGSVERWALTUNG=api-gateway-rechnungsverwaltung
      - PWRECHNUNGSVERWALTUNG=test
    ports:
      - 8010:8000

  rest-api-buchungsverwaltung2:
    networks:
      - service
      - architecture
    build: ./rest_api
    container_name: rest-api-buchungsverwaltung2
    environment:
      - DBUSER=admin
      - DBPWD=test1234
      - MONGODBROUTER=mongodb://buchungsverwaltung-single-db
      - ROOTPW=test
      - RECHNUNGSVERWALTUNG=api-gateway-rechnungsverwaltung
      - PWRECHNUNGSVERWALTUNG=test
    ports:
      - 8011:8000

  rest-api-buchungsverwaltung3:
    networks:
      - service
      - architecture
    build: ./rest_api
    container_name: rest-api-buchungsverwaltung3
    environment:
      - DBUSER=admin
      - DBPWD=test1234
      - MONGODBROUTER=mongodb://buchungsverwaltung-single-db
      - ROOTPW=test
      - RECHNUNGSVERWALTUNG=api-gateway-rechnungsverwaltung
      - PWRECHNUNGSVERWALTUNG=test
    ports:
      - 8012:8000

  api-gateway-buchungsverwaltung:
    container_name: api-gateway-buchungsverwaltung
    build: ./api_gateway
    networks:
      - service
      - architecture
    ports:
      - 8083:80
    depends_on:
      - rest-api-buchungsverwaltung1
      - rest-api-buchungsverwaltung2
      - rest-api-buchungsverwaltung3


  # um Nur eine Datenbank Instanz zu starten:
  buchungsverwaltung-single-db:
    networks:
      - service
      - architecture
    build: ./single_database
    container_name: buchungsverwaltung-single-db
    ports:
      - 27139:27017
